DROP TABLE PATH_SPEED_PATTERNS;

CREATE TABLE SPEED_PATTERNS_2013 (
  LINK_ID NUMBER,
  MONTH VARCHAR(10 BYTE),
  DAY VARCHAR(10 BYTE),
  TIME TIMESTAMP(6),
  SPEED NUMBER
);

INSERT INTO SPEED_PATTERNS_2013
SELECT LINK_ID, '', '', TO_TIMESTAMP(TIME, 'YYYY-MM-DD:HH24:MI'), SPEED
FROM SPEED_PATTERNS_ALLSENSORS_2013;

DELETE FROM PATH_SPEED_PATTERNS;

CREATE INDEX SPEED_PATTERNS_2013_TIME_IDX ON SPEED_PATTERNS_2013(TIME);
CREATE INDEX SPEED_PATTERNS_2013_LINK_IDX ON SPEED_PATTERNS_2013(LINK_ID);
CREATE INDEX SPEED_PATTERNS_2013_SPEED_IDX ON SPEED_PATTERNS_2013(SPEED);