SELECT DISTINCT SC.LINK_ID, t.Y, t.X, SC.DIRECTION 
FROM SENSOR_CONFIG SC, table(SDO_UTIL.GETVERTICES(SC.START_LAT_LONG)) t
WHERE SC.LINK_ID IN ( SELECT LINK_ID 
                      FROM (SELECT LINK_ID, COUNT(*) CNT
                            FROM SPEED_PATTERNS_2013
                            GROUP BY LINK_ID)
                      WHERE CNT > 59000)
ORDER BY SC.LINK_ID