SELECT T1.LINK_ID "FROM", T2.LINK_ID "TO", SDO_GEOM.SDO_DISTANCE(T1.GEOM, T2.GEOM, 0.001, 'UNIT=MILE') DISTANCE
FROM  (SELECT LINK_ID, GEOM FROM PATH##PATH_NUM##_SENSORS WHERE POSITION = ##FROM##) T1,
      (SELECT LINK_ID, GEOM FROM PATH##PATH_NUM##_SENSORS WHERE POSITION = ##TO##) T2