CREATE TABLE PATH##PATH_NUM##_EDGE_PATTERNS (
  "FROM" NUMBER,
  "TO" NUMBER,
  TIME TIMESTAMP(6),
  TRAVEL_TIME NUMBER
);
CREATE INDEX PATH##PATH_NUM##_EDGE_PATTERNS_TIME_IDX ON PATH##PATH_NUM##_EDGE_PATTERNS(TIME);