DROP TABLE PATH##PATH_NUM##_SENSORS;
DROP TABLE PATH##PATH_NUM##_EDGES;
DROP INDEX P##PATH_NUM##_SP_TIME_IDX;
DROP INDEX P##PATH_NUM##_SP_LINK_IDX;
DROP TABLE PATH##PATH_NUM##_SPEED_PATTERNS;
DROP INDEX P##PATH_NUM##_EP_TIME_IDX;
DROP INDEX P##PATH_NUM##_EP_TOD_IDX;
DROP TABLE PATH##PATH_NUM##_EDGE_PATTERNS