INSERT INTO TEMP VALUE
SELECT T1."FROM", T1."TO", T2.TIME FROM_TIME, T3.TIME TO_TIME, T2.SPEED FROM_SPEED, T3.SPEED TO_SPEED, T1.DISTANCE
FROM PATH##PATH_NUM##_EDGES T1, (PATH##PATH_NUM##_SPEED_PATTERNS T2 FULL OUTER JOIN PATH##PATH_NUM##_SPEED_PATTERNS T3 ON T2.TIME = T3.TIME)
WHERE T1."FROM" = T2.LINK_ID AND T1."TO" = T3.LINK_ID;
UPDATE TEMP SET FROM_TIME = TO_TIME, FROM_SPEED = TO_SPEED WHERE FROM_TIME = NULL;
UPDATE TEMP SET TO_TIME = FROM_TIME, TO_SPEED = FROM_SPEED WHERE TO_TIME = NULL