CREATE TABLE PATH##PATH_NUM##_SPEED_PATTERNS (
  LINK_ID NUMBER,
  MONTH VARCHAR(10 BYTE),
  DAY VARCHAR(10 BYTE),
  TIME TIMESTAMP(6),
  SPEED NUMBER
);
CREATE INDEX PATH##PATH_NUM##_SPEED_PATTERNS_TIME_IDX ON PATH##PATH_NUM##_SPEED_PATTERNS(TIME);
CREATE INDEX PATH##PATH_NUM##_SPEED_PATTERNS_LINK_IDX ON PATH##PATH_NUM##_SPEED_PATTERNS(LINK_ID);
CREATE INDEX PATH##PATH_NUM##_SPEED_PATTERNS_SPEED_IDX ON PATH##PATH_NUM##_SPEED_PATTERNS(SPEED);
INSERT INTO PATH##PATH_NUM##_SPEED_PATTERNS VALUE
SELECT *
FROM SPEED_PATTERNS_2013 T1
WHERE T1.LINK_ID IN (SELECT LINK_ID FROM PATH##PATH_NUM##_SENSORS);
CREATE TABLE TEMP (
  "FROM" NUMBER,
  "TO" NUMBER,
  FROM_TIME TIMESTAMP(6),
  TO_TIME TIMESTAMP(6),
  FROM_SPEED NUMBER,
  TO_SPEED NUMBER,
  DISTANCE NUMBER
);
INSERT INTO TEMP VALUE
SELECT T1."FROM", T1."TO", T2.TIME FROM_TIME, T3.TIME TO_TIME, T2.SPEED FROM_SPEED, T3.SPEED TO_SPEED, T1.DISTANCE
FROM PATH##PATH_NUM##_EDGES T1, (PATH##PATH_NUM##_SPEED_PATTERNS T2 FULL OUTER JOIN PATH##PATH_NUM##_SPEED_PATTERNS T3 ON T2.TIME = T3.TIME)
WHERE T1."FROM" = T2.LINK_ID AND T1."TO" = T3.LINK_ID;
UPDATE TEMP SET FROM_TIME = TO_TIME, FROM_SPEED = TO_SPEED WHERE FROM_TIME = NULL;
UPDATE TEMP SET TO_TIME = FROM_TIME, TO_SPEED = FROM_SPEED WHERE TO_TIME = NULL;
CREATE TABLE PATH##PATH_NUM##_EDGE_PATTERNS (
  "FROM" NUMBER,
  "TO" NUMBER,
  TIME TIMESTAMP(6),
  TRAVEL_TIME NUMBER
);
CREATE INDEX PATH##PATH_NUM##_EDGE_PATTERNS_TIME_IDX ON PATH##PATH_NUM##_EDGE_PATTERNS(TIME);
INSERT INTO PATH##PATH_NUM##_EDGE_PATTERNS
SELECT "FROM", "TO", FROM_TIME, (DISTANCE*2*3600)/(FROM_SPEED + TO_SPEED)
FROM TEMP;
DROP TABLE TEMP;