CREATE TABLE PATH##PATH_NUM##_SPEED_PATTERNS AS
SELECT *
FROM SPEED_PATTERNS_2013 T1
WHERE T1.LINK_ID IN (SELECT LINK_ID FROM PATH##PATH_NUM##_SENSORS);
CREATE INDEX P##PATH_NUM##_SP_TIME_IDX ON PATH##PATH_NUM##_SPEED_PATTERNS(TIME);
CREATE INDEX P##PATH_NUM##_SP_LINK_IDX ON PATH##PATH_NUM##_SPEED_PATTERNS(LINK_ID);
COMMIT;
CREATE TABLE TEMP AS
SELECT T1."FROM", T1."TO", T2.TIME FROM_TIME, T3.TIME TO_TIME, T2.SPEED FROM_SPEED, T3.SPEED TO_SPEED, T1.DISTANCE, T1.MAX_SPEED
FROM PATH##PATH_NUM##_EDGES T1, (PATH##PATH_NUM##_SPEED_PATTERNS T2 FULL OUTER JOIN PATH##PATH_NUM##_SPEED_PATTERNS T3 ON T2.TIME = T3.TIME)
WHERE T1."FROM" = T2.LINK_ID AND T1."TO" = T3.LINK_ID;
UPDATE TEMP SET FROM_TIME = TO_TIME, FROM_SPEED = TO_SPEED WHERE FROM_TIME = NULL;
UPDATE TEMP SET TO_TIME = FROM_TIME, TO_SPEED = FROM_SPEED WHERE TO_TIME = NULL;
COMMIT;
CREATE TABLE PATH##PATH_NUM##_EDGE_PATTERNS AS
SELECT "FROM", "TO", FROM_TIME AS TIME, TO_CHAR(FROM_TIME, 'DDD') AS DAY, TO_CHAR(FROM_TIME,'hh24:mi') AS TOD, (DISTANCE*2*3600)/(FROM_SPEED + TO_SPEED) AS TRAVEL_TIME,
CASE WHEN (DISTANCE*2)/(FROM_SPEED + TO_SPEED) > (DISTANCE*100)/(60*MAX_SPEED) THEN 'TRUE' ELSE 'FALSE' END AS CONG 
FROM TEMP;
COMMIT;
CREATE INDEX P##PATH_NUM##_EP_TIME_IDX ON PATH##PATH_NUM##_EDGE_PATTERNS(TIME);
CREATE INDEX P##PATH_NUM##_EP_TOD_IDX ON PATH##PATH_NUM##_EDGE_PATTERNS(TOD);
DROP TABLE TEMP;
COMMIT;